package com.yoona.community.mapper;

import com.yoona.community.model.COMMENT;
import com.yoona.community.model.COMMENTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface COMMENTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Sat Aug 07 21:54:29 CST 2021
     */
    long countByExample(COMMENTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Sat Aug 07 21:54:29 CST 2021
     */
    int deleteByExample(COMMENTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Sat Aug 07 21:54:29 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Sat Aug 07 21:54:29 CST 2021
     */
    int insert(COMMENT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Sat Aug 07 21:54:29 CST 2021
     */
    int insertSelective(COMMENT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Sat Aug 07 21:54:29 CST 2021
     */
    List<COMMENT> selectByExampleWithRowbounds(COMMENTExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Sat Aug 07 21:54:29 CST 2021
     */
    List<COMMENT> selectByExample(COMMENTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Sat Aug 07 21:54:29 CST 2021
     */
    COMMENT selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Sat Aug 07 21:54:29 CST 2021
     */
    int updateByExampleSelective(@Param("record") COMMENT record, @Param("example") COMMENTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Sat Aug 07 21:54:29 CST 2021
     */
    int updateByExample(@Param("record") COMMENT record, @Param("example") COMMENTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Sat Aug 07 21:54:29 CST 2021
     */
    int updateByPrimaryKeySelective(COMMENT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Sat Aug 07 21:54:29 CST 2021
     */
    int updateByPrimaryKey(COMMENT record);
}